name: Release Android APK

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: core/go.mod

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android NDK
        run: |
          sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "ndk;25.2.9519653"
          echo "ANDROID_NDK_HOME=${ANDROID_HOME}/ndk/25.2.9519653" >> $GITHUB_ENV

      - name: Build Go Daemon AAR
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          go install golang.org/x/mobile/cmd/gobind@latest
          ~/go/bin/gomobile init
          mkdir -p mobile/android/app/libs
          cd core
          ~/go/bin/gomobile bind -target=android/arm64 -androidapi 21 -ldflags="-checklinkname=0" -o ../mobile/android/app/libs/Daemon.aar ./daemon

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'any'
          channel: 'stable'

      - name: Build Android APK
        working-directory: mobile
        run: |
          mkdir -p ~/.config/.android ~/.android
          flutter pub get
          flutter build apk --release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: mobile/build/app/outputs/flutter-apk/app-release.apk
          name: PeerDrive Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
